export { default as Login } from './Login'
export { default as Dashboard } from './Dashboard'
export { default as Gallery } from './Gallery'
export { default as Reports } from './Reports'
export { default as Services } from './Services'
export { default as ProfileEdit } from './ProfileEdit'
export { default as ResetPassword } from './ResetPassword'